// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLO-omzDI0cWLKyoo5c3Wv41XCJj4sOjQ',
    appId: '1:318315632224:web:ce5c1f47515a61e22b5505',
    messagingSenderId: '318315632224',
    projectId: 'online-note-6f2cd',
    authDomain: 'online-note-6f2cd.firebaseapp.com',
    storageBucket: 'online-note-6f2cd.appspot.com',
    measurementId: 'G-8KNXFP4TNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtofaNcgGkhAxIKIR7KQ-9BgINTMwj-Ws',
    appId: '1:318315632224:android:25e1888a7430c15d2b5505',
    messagingSenderId: '318315632224',
    projectId: 'online-note-6f2cd',
    storageBucket: 'online-note-6f2cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1EdMYXdvBtcAZ5E6kC5bChOcdeIhQF58',
    appId: '1:318315632224:ios:da361085deecf31a2b5505',
    messagingSenderId: '318315632224',
    projectId: 'online-note-6f2cd',
    storageBucket: 'online-note-6f2cd.appspot.com',
    iosClientId: '318315632224-fkj182ehvkni6u481rme2qlvlagd6k55.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1EdMYXdvBtcAZ5E6kC5bChOcdeIhQF58',
    appId: '1:318315632224:ios:da361085deecf31a2b5505',
    messagingSenderId: '318315632224',
    projectId: 'online-note-6f2cd',
    storageBucket: 'online-note-6f2cd.appspot.com',
    iosClientId: '318315632224-fkj182ehvkni6u481rme2qlvlagd6k55.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineNote',
  );
}
